CREATE USER SOUPSI IDENTIFIED BY SOUPSI;
GRANT CONNECT TO SOUPSI;
GRANT CONNECT, RESOURCE, DBA TO SOUPSI;
GRANT UNLIMITED TABLESPACE TO SOUPSI;


CREATE TABLESPACE SOUPSI_DATA DATAFILE 'C:/Desenvolvimento/database/oracle/data/SOUPSI_DATA01.dbf' SIZE 50M EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
CREATE TABLESPACE SOUPSI_INDEX DATAFILE 'C:/Desenvolvimento/database/oracle/data/SOUPSI_INDEX01.dbf' SIZE 50M EXTENT MANAGEMENT LOCAL AUTOALLOCATE;


CREATE USER SOUPSI_CON IDENTIFIED BY SOUPSI_CON;
GRANT CONNECT TO SOUPSI_CON;
GRANT CONNECT, RESOURCE, DBA TO SOUPSI_CON;
GRANT UNLIMITED TABLESPACE TO SOUPSI_CON;