DROP TABLE SOUPSI.PESSOA_FISICA;

CREATE TABLE SOUPSI.PESSOA_FISICA (
	ID_PESSOA_FISICA NUMBER(11) NOT NULL,
	NOME VARCHAR2(255) NOT NULL
) TABLESPACE SOUPSI_DATA;

ALTER TABLE SOUPSI.PESSOA_FISICA ADD CONSTRAINT PK_PESSOA_FISICA PRIMARY KEY (ID_PESSOA_FISICA) USING INDEX TABLESPACE SOUPSI_INDEX;

GRANT SELECT, INSERT, UPDATE, DELETE ON SOUPSI.PESSOA_FISICA TO SOUPSI_CON;

DROP SEQUENCE SOUPSI.SQ_PESSOA_FISICA;
CREATE SEQUENCE SOUPSI.SQ_PESSOA_FISICA START WITH 1;
GRANT SELECT ON SOUPSI.SQ_PESSOA_FISICA TO SOUPSI_CON;